<?php
header("Content-type:application/json;charset=utf-8");
$fgsid = $_POST["fgsid"];
?>
{"code":0,"result":
	{
		"id":1,
		"xmmc":"广西项目2",
		"sgdw":"施工单位大大大",
		"aqzt":0,
		"tjzs":10,
		"tjzxs":3,
		"tjjrczs":1,
		"yhtjs":1,
		"sjjzs":3,
		"sjjzxs":1,
		"sjjjrczs":0
	}
}